"""initial schema

Revision ID: 704b507ce854
Revises: d010d5788af0
Create Date: 2026-07-28 17:07:24.792560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '704b507ce854'
down_revision: Union[str, None] = 'd010d5788af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lenders',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=128), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_exposure_limit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('api_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('name')
    )
    op.create_table('loan_types',
    sa.Column('code', sa.Enum('SALARY_ADVANCE', 'PERSONAL_LOAN', 'EMERGENCY_LOAN', 'EDUCATION_LOAN', 'MEDICAL_LOAN', name='loan_type_code_enum'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_tenure_months', sa.Integer(), nullable=False),
    sa.Column('max_tenure_months', sa.Integer(), nullable=False),
    sa.Column('requires_collateral', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('EMPLOYEE', 'EMPLOYER_ADMIN', 'LENDER', 'PLATFORM_ADMIN', 'SUPPORT', name='user_type_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('employers',
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('employee_count_band', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'TERMINATED', name='employer_status_enum'), nullable=False),
    sa.Column('payroll_cycle_day', sa.Integer(), nullable=False),
    sa.Column('max_salary_advance_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_user_id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('interest_rates',
    sa.Column('lender_id', sa.UUID(), nullable=False),
    sa.Column('loan_type_id', sa.UUID(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('annual_rate_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('processing_fee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_rates_lender_id'), 'interest_rates', ['lender_id'], unique=False)
    op.create_index(op.f('ix_interest_rates_loan_type_id'), 'interest_rates', ['loan_type_id'], unique=False)
    op.create_table('loan_policies',
    sa.Column('loan_type_id', sa.UUID(), nullable=False),
    sa.Column('min_tenure_months_employed', sa.Integer(), nullable=False),
    sa.Column('min_career_credit_score', sa.Integer(), nullable=False),
    sa.Column('max_dti_ratio', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_active_loans', sa.Integer(), nullable=False),
    sa.Column('max_pct_of_monthly_salary', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cooling_period_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_policies_loan_type_id'), 'loan_policies', ['loan_type_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', 'IN_APP', name='notification_channel_enum'), nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'READ', name='notification_status_enum'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('otps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('LOGIN', 'EMAIL_VERIFICATION', 'PHONE_VERIFICATION', 'PASSWORD_RESET', 'MFA', name='otp_purpose_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('departments',
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cost_center_code', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employer_id', 'name', name='uq_department_employer_name')
    )
    op.create_index(op.f('ix_departments_employer_id'), 'departments', ['employer_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_type', sa.Enum('MONTHLY_PORTFOLIO', 'EMPLOYER_UTILIZATION', 'FRAUD_SUMMARY', 'NPA_REPORT', 'COLLECTIONS', name='report_type_enum'), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('employer_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'GENERATING', 'READY', 'FAILED', name='report_status_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('employee_code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=128), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'ON_LEAVE', 'SUSPENDED', 'RESIGNED', 'TERMINATED', name='employment_status_enum'), nullable=False),
    sa.Column('pan_encrypted', sa.String(length=512), nullable=True),
    sa.Column('aadhaar_encrypted', sa.String(length=512), nullable=True),
    sa.Column('bank_account_encrypted', sa.String(length=512), nullable=True),
    sa.Column('ifsc_code', sa.String(length=16), nullable=True),
    sa.Column('monthly_gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employer_id', 'employee_code', name='uq_employee_employer_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_employees_employer_id'), 'employees', ['employer_id'], unique=False)
    op.create_table('career_credit_scores',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('employment_stability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('salary_growth_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('attendance_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('promotion_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('performance_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('repayment_behavior_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('feature_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_credit_scores_employee_id'), 'career_credit_scores', ['employee_id'], unique=False)
    op.create_table('documents',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('PAN_CARD', 'AADHAAR', 'SALARY_SLIP', 'BANK_STATEMENT', 'OFFER_LETTER', 'ADDRESS_PROOF', 'SELFIE', 'OTHER', name='document_type_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'OCR_PROCESSING', 'OCR_COMPLETE', 'VERIFIED', 'REJECTED', 'FLAGGED_SUSPICIOUS', name='document_status_enum'), nullable=False),
    sa.Column('ocr_extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('forgery_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_employee_id'), 'documents', ['employee_id'], unique=False)
    op.create_index(op.f('ix_documents_file_hash_sha256'), 'documents', ['file_hash_sha256'], unique=False)
    op.create_table('financial_wellness_records',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('debt_to_income_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('savings_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('emi_burden_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('loan_utilization_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('emergency_reserve_months', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('wellness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('wellness_band', sa.String(length=16), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_wellness_records_employee_id'), 'financial_wellness_records', ['employee_id'], unique=False)
    op.create_table('kyc_records',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'PENDING_REVIEW', 'VERIFIED', 'REJECTED', name='kyc_status_enum'), nullable=False),
    sa.Column('pan_verified', sa.Boolean(), nullable=False),
    sa.Column('aadhaar_verified', sa.Boolean(), nullable=False),
    sa.Column('bank_account_verified', sa.Boolean(), nullable=False),
    sa.Column('liveness_check_passed', sa.Boolean(), nullable=False),
    sa.Column('face_match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('loan_applications',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('loan_type_id', sa.UUID(), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requested_tenure_months', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_AI_REVIEW', 'UNDER_MANUAL_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'FLAGGED_FRAUD', name='loan_application_status_enum'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decisioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_employee_id'), 'loan_applications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_loan_type_id'), 'loan_applications', ['loan_type_id'], unique=False)
    op.create_table('payrolls',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('cycle_month', sa.Integer(), nullable=False),
    sa.Column('cycle_year', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('emi_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('days_present', sa.Integer(), nullable=True),
    sa.Column('days_absent', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='payroll_status_enum'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'cycle_month', 'cycle_year', name='uq_payroll_employee_cycle')
    )
    op.create_index(op.f('ix_payrolls_employee_id'), 'payrolls', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payrolls_employer_id'), 'payrolls', ['employer_id'], unique=False)
    op.create_table('ai_predictions',
    sa.Column('loan_application_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('prediction_type', sa.Enum('ELIGIBILITY', 'FRAUD', 'CAREER_SCORE', 'WELLNESS', name='prediction_type_enum'), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('approval_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('eligible_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inference_latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_application_id')
    )
    op.create_index(op.f('ix_ai_predictions_employee_id'), 'ai_predictions', ['employee_id'], unique=False)
    op.create_table('fraud_alerts',
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('loan_application_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='fraud_alert_severity_enum'), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_INVESTIGATION', 'CONFIRMED', 'DISMISSED', name='fraud_alert_status_enum'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_alerts_employee_id'), 'fraud_alerts', ['employee_id'], unique=False)
    op.create_table('loans',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('lender_id', sa.UUID(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('processing_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('disbursed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'DEFAULTED', 'WRITTEN_OFF', 'RESTRUCTURED', name='loan_status_enum'), nullable=False),
    sa.Column('outstanding_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_loans_employee_id'), 'loans', ['employee_id'], unique=False)
    op.create_index(op.f('ix_loans_lender_id'), 'loans', ['lender_id'], unique=False)
    op.create_table('emis',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_component', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_component', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'DUE', 'PAID', 'OVERDUE', 'PARTIALLY_PAID', 'WAIVED', name='emi_status_enum'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('late_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emis_due_date'), 'emis', ['due_date'], unique=False)
    op.create_index(op.f('ix_emis_loan_id'), 'emis', ['loan_id'], unique=False)
    op.create_table('transactions',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=True),
    sa.Column('emi_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.Enum('DISBURSEMENT', 'EMI_PAYMENT', 'LATE_FEE', 'REFUND', 'PROCESSING_FEE', 'PAYROLL_DEDUCTION', name='transaction_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REVERSED', name='transaction_status_enum'), nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=False),
    sa.Column('payment_gateway_ref', sa.String(length=128), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emi_id'], ['emis.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id')
    )
    op.create_index(op.f('ix_transactions_employee_id'), 'transactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_transactions_loan_id'), 'transactions', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_loan_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_employee_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_emis_loan_id'), table_name='emis')
    op.drop_index(op.f('ix_emis_due_date'), table_name='emis')
    op.drop_table('emis')
    op.drop_index(op.f('ix_loans_lender_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_employee_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_fraud_alerts_employee_id'), table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    op.drop_index(op.f('ix_ai_predictions_employee_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_payrolls_employer_id'), table_name='payrolls')
    op.drop_index(op.f('ix_payrolls_employee_id'), table_name='payrolls')
    op.drop_table('payrolls')
    op.drop_index(op.f('ix_loan_applications_loan_type_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_employee_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_table('kyc_records')
    op.drop_index(op.f('ix_financial_wellness_records_employee_id'), table_name='financial_wellness_records')
    op.drop_table('financial_wellness_records')
    op.drop_index(op.f('ix_documents_file_hash_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_employee_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_career_credit_scores_employee_id'), table_name='career_credit_scores')
    op.drop_table('career_credit_scores')
    op.drop_index(op.f('ix_employees_employer_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('reports')
    op.drop_index(op.f('ix_departments_employer_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_loan_policies_loan_type_id'), table_name='loan_policies')
    op.drop_table('loan_policies')
    op.drop_index(op.f('ix_interest_rates_loan_type_id'), table_name='interest_rates')
    op.drop_index(op.f('ix_interest_rates_lender_id'), table_name='interest_rates')
    op.drop_table('interest_rates')
    op.drop_table('employers')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('loan_types')
    op.drop_table('lenders')
    # ### end Alembic commands ###
